### ISSUE TITLE
Monthly Consumption Report: the "closing balance" and "stock on hand"  should always be the same value as the "STOCK ON HAND", however, "closing balance" updates and remains as the "STOCK ON HAND" on the last day of the month. "Opening Balance" equals "STOCK ON HAND" on the first day of the month and does not change

### ISSUE THREAD

**Issue by chai-lmis** [clintonhealthaccess/chailmis-android#262]

**Comment by chai-lmis** [comment]
Example: if 
Stock on Hand on 1st Oct = 150, Opening Balance = 150, Closing Balance for Oct = 150
Stock on Hand on 15th Oct = 70, Opening Balance = 150 (Stock on Hand on 1st Oct ), closing balance for Oct= 70
Stock on Hand on 31st Oct = 120, Opening Balance = 150 (Stock on Hand on 1st Oct ), closing balance for Oct = 120 
Stock on Hand on 1st Nov = 100, Opening Balance = 100, closing balance for Nov= 100
....

**Comment by garymabin** [comment]
@chai-lmis, just would like to confirm that will we change the Opening Balance and Closing Balance for all the Monthly Reports or just "Monthly Facility Consumption Report RH2"?

**Comment by chai-lmis** [comment]
all the reports should be changed

**Comment by ihassin** [comment]
@bin and I will discuss this during tonight's meeting. I'd like to get an estimate on this prior to starting work on it.

**Comment by garymabin** [comment]
Fixed f8c5c97

**Comment by chai-lmis** [comment]
This is not fixed, the Stock on Hand values on the "Monthly Report" is zero for all commodities on all the reports

**Comment by chai-lmis** [comment]
Tested: OK
